### ISSUE TITLE
deis pull fails with No Tag Found

### ISSUE THREAD

**Issue by mvanholsteijn** [deis/deis#3116]
We are trying to pull a docker image from the repository, and it fails with the message "Tag not found"

$ deis pull mvanholsteijn/paas-monitor:1.1 --app pmon

Creating build... 503 SERVICE UNAVAILABLE
Detail:
GET Image Error (404: {"error": "Tag not found"})

In the deis-builder log, the following error appears:

Feb 20 13:04:12 ip-10-21-1-78.eu-west-1.compute.internal sh:  [error] pull.go:149 Error from V2 registry: error verifying manifest: error parsing payload: error unmarshalling public key: JWK EC Public Key ID does not match: OIH7:HQFS:44FK:45VB:3B53:OIAG:TPL4:ATF5:6PNE:MGHN:NHQX:2GE4

**Comment by daemonza** [comment]
Have a look here
https://github.com/deis/deis/issues/2916

Might be related.

**Comment by carmstrong** [comment]
> Have a look here
> #2916

Yes, we're hoping the "Tag not found" errors are fixed by changes which will land in Deis v1.4.0.

@mvanholsteijn Please upgrade to v1.4.0 when it releases and see if this error goes away. In the meantime, try another `deis pull` - this issue is hopefully sporadic.

**Comment by sbuss** [comment]
It's worth mentioning that this happened to me when the deis-cache (redis lru cache) ran out of memory. See the IRC discussion here: https://botbot.me/freenode/deis/2015-01-15/?msg=29721039&page=4

The issue went away when I stopped deis-cache and restarted deis-registry so it would work without the cache.

**Comment by carmstrong** [comment]
Deis v1.4.0 is out. I'm going to close this issue, but please reopen if you're still seeing this after upgrading to v1.4.0.

**Comment by synaptics** [comment]
I've just upgrade (in-place) from Deis 1.2.1 to 1.4.0 and this problem persists for me.  Any advice?

Thanks.

**Comment by bacongobbler** [comment]
@synaptics could you please gist the following?

```
deisctl journal controller
deisctl journal registry@1
deisctl journal cache
```

**Comment by synaptics** [comment]
Sure, the output is here: https://gist.github.com/synaptics/9693c194fee7ae5a46e4

**Comment by bacongobbler** [comment]
Sorry, forgot that `deisctl journal` only shows a very small snippet. Could you please show:

```
fleetctl ssh deis-controller docker logs deis-controller
fleetctl ssh deis-registry@1 docker logs deis-registry
fleetctl ssh deis-cache docker logs deis-cache
```

You'll have to set up SSH agent forwarding in order for this to work if you're using `fleetctl` on one of the CoreOS nodes: https://github.com/coreos/fleet/blob/master/Documentation/using-the-client.md#exploring-the-cluster

**Comment by aledbf** [comment]
from the logs: `POST /v1/repositories/demo/tags HTTP/1.1" 500 84`
It means that you need to run `deis pull again` (you did it twice)

**Comment by carmstrong** [comment]
It sounds like this is still an issue in v1.4.0

**Comment by particlebanana** [comment]
Following @sbuss idea I disabled the cache layer on a fresh aws instance and restarted the registry and `pull` started working.

**Comment by daemonza** [comment]
Upgraded to 1.4.0 and I don't experience the issue anymore on a stack in AWS

**Comment by synaptics** [comment]
Hi,

New gist with output from

fleetctl ssh deis-controller docker logs deis-controller
fleetctl ssh deis-registry@1 docker logs deis-registry
fleetctl ssh deis-cache docker logs deis-cache

is here -> https://gist.github.com/synaptics/d9b30f122f8422eca473

I ran deis pull a couple of times and it made no difference, I got the same issue.  

I notice in the dies-registry output a large number of connections dropped to can-registry-1.docker.io for some reason.  The cluster is on AWS spun up via the Deis cloud formation, it's in eu-west-1.

Thanks again for looking at this.

**Comment by bacongobbler** [comment]
@synaptics can you try disabling the cache and see how it goes (`deisctl stop cache`)? See https://github.com/deis/deis/issues/3116#issuecomment-77472068 and https://github.com/deis/deis/issues/2916#issuecomment-70724734

**Comment by synaptics** [comment]
@bacongobbler Gives a very similar result with the cache off:

john:~$ deis pull gabrtv/example-go:latest -a demo
Creating build... 404 NOT FOUND
Detail:
Not found

**Comment by bacongobbler** [comment]
@synaptics if you're available, I'd be happy to help you more on IRC so we can get to the bottom of this

**Comment by synaptics** [comment]
@bacongobbler unfortunately I've run out of time to do any more this today, but am around on Monday if you're free then?

**Comment by bacongobbler** [comment]
I'm off on monday for my birthday :cake: 

Just ping me on IRC when you have time :)

**Comment by carmstrong** [comment]
Hi folks, I created #3218 to track this, since there are a few conversations about it split across various issues. Let's get to the bottom of things over there.

**Comment by apps4u** [comment]
Hi Im on 1.4.1 and Im getting this issue wether I use private docker reg or docker hub ,, here is journal from registry@1

Mar 09 08:52:26 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:52:26 +0000] "PUT /v1/repositories/preset-chinbone/tags/v0 HTTP/1.1" 200 4 "-" "docker/1.0.0"
Mar 09 08:52:26 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:52:26 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:52:26 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:52:26 +0000] "GET /v1/repositories/preset-chinbone/tags/latest HTTP/1.1" 404 26 "-" "docker/1.0.0"
Mar 09 08:54:40 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:54:40 +0000 INFO: Resetting dropped connection: registry.hub.docker.com
Mar 09 08:54:41 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:54:41 +0000 INFO: Resetting dropped connection: registry.hub.docker.com
Mar 09 08:54:42 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:54:42 +0000 INFO: Resetting dropped connection: cdn-registry-1.docker.io
Mar 09 08:54:43 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:54:43 +0000 INFO: Resetting dropped connection: cdn-registry-1.docker.io
Mar 09 08:54:44 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:54:44 +0000 INFO: Resetting dropped connection: dseasb33srnrn.cloudfront.net
Mar 09 08:54:53 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:54:53 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:54:53 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:54:53 +0000] "POST /v1/repositories/mathics2/tags HTTP/1.1" 500 84 "-" "python-requests/2.4.3 CPython/2.7.6 Linux/3.18.1"
Mar 09 08:54:53 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:54:53 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:54:53 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:54:53 +0000] "GET /v1/repositories/mathics2/tags/latest HTTP/1.1" 404 26 "-" "docker/1.0.0"
Mar 09 08:54:53 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:54:53 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:54:53 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:54:53 +0000] "PUT /v1/images/f466490e4de04db4aa037b1969a35e73f466490e4de04db4aa037b1969a35e73/json HTTP/1.1" 200 4 "-" "docker/1.0.0"
Mar 09 08:54:53 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:54:53 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:54:53 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:54:53 +0000] "PUT /v1/images/f466490e4de04db4aa037b1969a35e73f466490e4de04db4aa037b1969a35e73/layer HTTP/1.1" 200 4 "-" "docker/1.0.0"
Mar 09 08:54:53 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:54:53 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:54:53 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:54:53 +0000] "PUT /v1/images/f466490e4de04db4aa037b1969a35e73f466490e4de04db4aa037b1969a35e73/checksum HTTP/1.1" 200 4 "-" "docker/1.0.0"
Mar 09 08:54:53 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:54:53 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:54:53 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:54:53 +0000] "PUT /v1/repositories/mathics2/tags/v0 HTTP/1.1" 200 4 "-" "docker/1.0.0"
Mar 09 08:54:54 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:54:54 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:54:54 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:54:54 +0000] "GET /v1/repositories/mathics2/tags/latest HTTP/1.1" 404 26 "-" "docker/1.0.0"
Mar 09 08:57:42 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:57:42 +0000 INFO: Resetting dropped connection: registry.hub.docker.com
Mar 09 08:57:43 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:57:43 +0000 INFO: Resetting dropped connection: registry.hub.docker.com
Mar 09 08:57:45 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:57:45 +0000 INFO: Resetting dropped connection: cdn-registry-1.docker.io
Mar 09 08:57:46 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:57:46 +0000 INFO: Resetting dropped connection: dseasb33srnrn.cloudfront.net
Mar 09 08:57:55 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:57:55 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:57:55 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:57:55 +0000] "POST /v1/repositories/truthy-aqualung/tags HTTP/1.1" 500 84 "-" "python-requests/2.4.3 CPython/2.7.6 Linux/3.18.1"
Mar 09 08:57:57 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:57:57 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:57:57 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:57:57 +0000] "GET /v1/repositories/truthy-aqualung/tags/latest HTTP/1.1" 404 26 "-" "docker/1.0.0"
Mar 09 08:57:57 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:57:57 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:57:57 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:57:57 +0000] "PUT /v1/images/666c39090b5b4fb799988de59059b1e9666c39090b5b4fb799988de59059b1e9/json HTTP/1.1" 200 4 "-" "docker/1.0.0"
Mar 09 08:57:57 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:57:57 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:57:57 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:57:57 +0000] "PUT /v1/images/666c39090b5b4fb799988de59059b1e9666c39090b5b4fb799988de59059b1e9/layer HTTP/1.1" 200 4 "-" "docker/1.0.0"
Mar 09 08:57:57 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:57:57 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:57:57 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:57:57 +0000] "PUT /v1/images/666c39090b5b4fb799988de59059b1e9666c39090b5b4fb799988de59059b1e9/checksum HTTP/1.1" 200 4 "-" "docker/1.0.0"
Mar 09 08:57:57 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:57:57 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:57:57 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:57:57 +0000] "PUT /v1/repositories/truthy-aqualung/tags/v0 HTTP/1.1" 200 4 "-" "docker/1.0.0"
Mar 09 08:57:57 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 09/Mar/2015:08:57:57 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Mar 09 08:57:57 ip-10-21-1-34.ap-southeast-2.compute.internal sh[4240]: 172.17.42.1 - - [09/Mar/2015:08:57:57 +0000] "GET /v1/repositories/truthy-aqualung/tags/latest HTTP/1.1" 404 26 "-" "docker/1.0.0"

**Comment by apps4u** [comment]
Ive read about issue  #3218  Im going to change REDIS config and try agin and give feed back if that helps.

**Comment by fretboarder** [comment]
I have installed a fresh DEIS 1.5.1 cluster and I'm getting the 503 error when trying to pull from a private registry. Pulling from the docker hub works without problems.
I also noticed that DEIS doesn't install the cache anymore. Is that a wanted behavior or is it a bug?/

**Comment by Joshua-Anderson** [comment]
> I also noticed that DEIS doesn't install the cache anymore. Is that a wanted behavior or is it a bug?

It is intentional, the deis team disabled it in a attempt to combat #3218.

**Comment by bacongobbler** [comment]
Indeed. @fretboarder you may want to subscribe to #2870 to follow that feature request.

**Comment by fretboarder** [comment]
Something weird is happening here:

cluster 1 is an DEIS installation that I have upgraded to 1.5.1 from 1.4.1
cluster 2 is a brand new 1.5.1 installation.

> Deis doesn't support private repositories at the moment.
I can't confirm that. On my cluster 1 I'm definitely (still?) able to pull from a private registry.

I'm using the default registry image https://registry.hub.docker.com/_/registry/ for my private registries. The only difference is that on cluster 1 the registry is running on an Ubuntu/Docker 14.04 host whereas on cluster 2 the registry is running on CoreOS/Docker. Both have docker version 1.5.

Any ideas?

**Comment by bacongobbler** [comment]
I think you two are just getting confused. @Joshua-Anderson is correct that you cannot pull from a private *repository* on DockerHub. You should be able to pull from a private *registry*.

@fretboarder could you please open a new issue for this and post your logs there? This sounds like a different issue.
